import 'package:stage/model/article.dart';

class Utils_article {
  static List<Article> getMockedArticle() {
    return [
      Article(
        titre: "Urbaine", 
        titre1:"Tradionnel",
        titre2:"",
        titre3:"",
        titre4:"",
        desc: "Danser la musique urbaine", 
        desc1:"Ecouter de la tradi",
        desc2:"",
        desc3:"",
        desc4:"",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"",
        img3:"",
        img4:"",
        codeCategorie: "Musique"),

        Article(
        titre: "Santé ", 
        titre1:"Santé Plus",
        titre2:"",
        titre3:"",
        titre4:"",
        desc: "Découvrez la santé dans le monde", 
        desc1:"Plus d'info sur la santé",
        desc2:"",
        desc3:"",
        desc4:"",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"",
        img3:"",
        img4:"",
        codeCategorie: "Santé et Sécurité"),

        Article(
        titre: "faceboock", 
        titre1:"Messenger",
        titre2:"Linkedin",
        titre3:"Twiter",
        titre4:"Instagram",
        desc: "Connecté avec votre compte", 
        desc1:"connecté vous avec votre compte",
        desc2:"connecté vous avec votre compte",
        desc3:"connecté vous avec votre compte",
        desc4:"connecté vous avec votre compte",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"assets/logo.png",
        img3:"assets/logo.png",
        img4:"assets/logo.png",
        codeCategorie: "Communication"),

        Article(
        titre: "e-commerce", 
        titre1:"Affaire",
        titre2:"e-commerce",
        titre3:"Affaire",
        titre4:"e-commerce",
        desc: "Joindre le monde de business", 
        desc1:"Joindre le monde de business",
        desc2:"Joindre le monde de business",
        desc3:"Joindre le monde de business",
        desc4:"Joindre le monde de business",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"assets/logo.png",
        img3:"assets/logo.png",
        img4:"assets/logo.png",
        codeCategorie: "Business"),

        Article(
        titre: "Traiding", 
        titre1:"Photoshop",
        titre2:"Ux/Ui design",
        titre3:"Graphisme",
        titre4:"CCNA",
        desc: "Suivez des formations gratuites", 
        desc1:"Suivez des formations gratuites",
        desc2:"Suivez des formations gratuites",
        desc3:"Suivez des formations gratuites",
        desc4:"Suivez des formations gratuites",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"assets/logo.png",
        img3:"assets/logo.png",
        img4:"assets/logo.png",
        codeCategorie: "Formation"),

        Article(
        titre: "covid-19", 
        titre1:"Paludisme",
        titre2:"EBOLA",
        titre3:"OMICRON",
        titre4:"LASSA",
        desc: "Avoir les nouvelles infos sur covid-19", 
        desc1:"Avoir les nouvelles infos sur paludisme",
        desc2:"Avoir les nouvelles infos sur EBOLA",
        desc3:"Avoir les nouvelles infos sur OMICRON",
        desc4:"Avoir les nouvelles infos sur LASSA",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"assets/logo.png",
        img3:"assets/logo.png",
        img4:"assets/logo.png",
        codeCategorie: "Information sur le coronavirus"),

        Article(
        titre: "Méteo", 
        titre1:"Atmosphere",
        titre2:"Méteo",
        titre3:"Atmosphere",
        titre4:"Atmosphere",
        desc: "Avoir les nouvelles", 
        desc1:"Avoir les nouvelles sur la nature",
        desc2:"Avoir les nouvelles sur la nature",
        desc3:"Avoir les nouvelles sur la nature",
        desc4:"Avoir les nouvelles sur la nature",
        img:"assets/logo.png",
        img1:"assets/logo.png",
        img2:"assets/logo.png",
        img3:"assets/logo.png",
        img4:"assets/logo.png",
        codeCategorie: "Méteo"),
    ];
  }
}
